apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-blue
  namespace: opensearch
spec:
  general:
    httpPort: 9200
    serviceName: opensearch-blue
    version: 2.11.1
    drainDataNodes: true
    setVMMaxMapCount: true
    pluginsList: ["repository-gcs"]
    keystore:
      - secret:
          name: gcp-credentials
    monitoring:
      enable: true
      scrapeInterval: 30s 
      pluginUrl: https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/releases/download/2.11.1.0/prometheus-exporter-2.11.1.0.zip
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: 30Gi
      resources:
         requests:
            memory: "4Gi"
            cpu: "1000m"
         limits:
            memory: "4Gi"
            cpu: "1000m"
      roles:
        - "cluster_manager"
        - "data"
      persistence:
        pvc:
          storageClass: premium-rwo
          accessModes:
          - ReadWriteOnce